version: '3.9'
name: nursing_kku
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./web/Dockerfile  #ตำแหน่งที่อยู่ dockerfile ของ web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php/Dockerfile  #ตำแหน่งที่อยู่ dockerfile ของ php
    volumes:
      - ./src:/var/www/html

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin #ใช้ images ของ phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "8081:80"

  mysql:
    restart: unless-stopped
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: adminkku
      MYSQL_DATABASE: nursing_kku
      MYSQL_USER: kku
      MYSQL_PASSWORD: kku


  nodejs_app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile  # ให้แน่ใจว่า Dockerfile อยู่ใน root directory
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src  # ปรับเปลี่ยนตามโครงสร้างโฟลเดอร์ของโปรเจกต์
      - /usr/src/app/node_modules  # ไม่ต้องมี node_modules ใน volume, จะถูกสร้างใน image