version: '3.9'
name: nursing_kku
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./web/Dockerfile  #ตำแหน่งที่อยู่ dockerfile ของ web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nursing_network


  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php/Dockerfile  #ตำแหน่งที่อยู่ dockerfile ของ php
    volumes:
      - ./src:/var/www/html
    networks:
      - nursing_network

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin #ใช้ images ของ phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      - nursing_network

  mysql:
    restart: unless-stopped
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: adminkku
      MYSQL_DATABASE: nu_service
      MYSQL_USER: kku
      MYSQL_PASSWORD: kku
    networks:
      - nursing_network
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=caching_sha2_password

  api-service-nu:
    build:
      context: ./backend
      dockerfile: Dockerfile  # ให้แน่ใจว่า Dockerfile อยู่ใน root directory
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: kku
      DB_PASSWORD: kku
      DB_DATABASE: nu_service
    networks:
      - nursing_network

networks:
  nursing_network:
    driver: bridge
    