version: '3.9'
name: nursing_kku
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      nursing_network:
        ipv4_address: 192.168.10.2

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      nursing_network:
        ipv4_address: 192.168.10.3

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    ports:
      - "8081:80"
    networks:
      nursing_network:
        ipv4_address: 192.168.10.4

  mysql:
    restart: unless-stopped
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: adminkku
      MYSQL_DATABASE: nu_service
      MYSQL_USER: kku
      MYSQL_PASSWORD: kku
    networks:
      nursing_network:
        ipv4_address: 192.168.10.5
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=caching_sha2_password

  api-service-nu:
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: kku
      DB_PASSWORD: kku
      DB_DATABASE: nu_service
    networks:
      nursing_network:
        ipv4_address: 192.168.10.6

  cloudflared:
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token eyJhIjoiOWE1YThkZTAxODQxYjUwZjJiYWIwZGQ1YTQzZjU4NzEiLCJ0IjoiYTA3YmNmYzYtNjk1Ni00YzFjLWJhYjQtYmZhNmRlNmRlM2ExIiwicyI6Ik1qZGpPRFJqWkdVdFpEZzNNQzAwTlRNMExUa3laRE10TUdJd1pHSXpPV1F5T0dFeCJ9
    networks:
      nursing_network:
        ipv4_address: 192.168.10.7

networks:
  nursing_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24

volumes:
  web_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/srv/docker_data/web'  # เปลี่ยนเป็นที่อยู่ของโฟลเดอร์บนเครื่องโฮสต์ที่คุณต้องการเชื่อมต่อกับ container