version: '3.9'
name: nursing_kku
services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./web/Dockerfile  #ตำแหน่งที่อยู่ dockerfile ของ web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf

  php:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./php/Dockerfile  #ตำแหน่งที่อยู่ dockerfile ของ php
    volumes:
      - ./src:/var/www/html

  phpmyadmin:
    restart: unless-stopped
    image: phpmyadmin/phpmyadmin #ใช้ images ของ phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mariadb
    depends_on:
      - mariadb
    ports:
      - "8081:80"

  mariadb:
    restart: unless-stopped
    image: mariadb:10.8     #ใช้ images ของ mariadb version 10.8
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "kku"
      MYSQL_DATABASE: nursing_kku