# Use an official Node.js runtime as a parent image
FROM node:14

WORKDIR /app
 
COPY ./backend/package.json ./backend/package-lock.json /app/
COPY ./backend/ /app/
 
RUN npm install
 
COPY . .
 
CMD [ "node", "index.js" ]